In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [3]:
ds = pd.read_csv('scopus1.csv')
ds.head()

Authors  \
0                                          Shor P.W.   
1                      Philip Chen C.L., Zhang C.-Y.   
2  Bennett C.H., Bessette F., Brassard G., Salvai...   
3                               Han K.-H., Kim J.-H.   
4  Kendall R.A., Aprà E., Bernholdt D.E., Bylaska...   

                                        Author(s) ID  \
0                                        7005883316;   
1                           47861886300;56072612200;   
2  7401715072;16418241300;7003764522;6602312387;6...   
3                           35956099400;36484629700;   
4  35551180400;6603601682;6603558471;6701463104;7...   

                                               Title  Year  \
0  Polynomial-time algorithms for prime factoriza...  1997   
1  Data-intensive applications, challenges, techn...  2014   
2                  Experimental quantum cryptography  1992   
3  Quantum-inspired evolutionary algorithm for a ...  2002   
4  High performance computational chemistry: an o...  2000   

                                    Source title Volume Issue Art. No.  \
0                      SIAM Journal on Computing     26     5      NaN   
1                           Information Sciences    275   NaN      NaN   
2                          Journal of Cryptology      5     1      NaN   
3  IEEE Transactions on Evolutionary Computation      6     6      NaN   
4                Computer Physics Communications    128     1      NaN   

  Page start Page end  Page count  Cited by                            DOI  \
0       1484     1509         NaN    3391.0      10.1137/S0097539795293172   
1        314      347         NaN    1378.0      10.1016/j.ins.2014.01.015   
2          3       28         NaN    1290.0             10.1007/BF00191318   
3        580      593         NaN    1100.0       10.1109/TEVC.2002.804320   
4        260      283         NaN     663.0  10.1016/S0010-4655(00)00065-5   

                                                Link  \
0  https://www.scopus.com/inward/record.uri?eid=2...   
1  https://www.scopus.com/inward/record.uri?eid=2...   
2  https://www.scopus.com/inward/record.uri?eid=2...   
3  https://www.scopus.com/inward/record.uri?eid=2...   
4  https://www.scopus.com/inward/record.uri?eid=2...   

                              Correspondence Address  \
0  Shor, P.W.; AT and T Labs.-Research, 180 Park ...   
1  Philip Chen, C.L.; Department of Computer and ...   
2  Bennett, C.H.; IBM Research, Yorktown Heights,...   
3  Han, K.-H.; Dept. of Elec. Eng. and Comp. Sci....   
4  Kendall, Ricky A.; Ames Lab, Ames, IA, United ...   

                                           Publisher Document Type  \
0  Society for Industrial and Applied Mathematics...       Article   
1                                      Elsevier Inc.       Article   
2                                    Springer-Verlag       Article   
3                                                NaN       Article   
4        Elsevier Science Publishers B.V., Amsterdam       Article   

  Publication Stage  Source                 EID  
0             Final  Scopus   2-s2.0-0142051871  
1             Final  Scopus  2-s2.0-84900800509  
2             Final  Scopus   2-s2.0-0026626314  
3             Final  Scopus   2-s2.0-0036945847  
4             Final  Scopus   2-s2.0-0034625269

In [4]:
ds.isna().sum()

Authors                      0
Author(s) ID                 0
Title                        0
Year                         0
Source title                 0
Volume                      20
Issue                      331
Art. No.                  1600
Page start                 253
Page end                   254
Page count                1994
Cited by                    82
DOI                        258
Link                         0
Correspondence Address     197
Publisher                  883
Document Type                0
Publication Stage            0
Source                       0
EID                          0
dtype: int64

In [5]:
len(ds)

2000

In [6]:
ds.columns

Index(['Authors', 'Author(s) ID', 'Title', 'Year', 'Source title', 'Volume',
       'Issue', 'Art. No.', 'Page start', 'Page end', 'Page count', 'Cited by',
       'DOI', 'Link', 'Correspondence Address', 'Publisher', 'Document Type',
       'Publication Stage', 'Source', 'EID'],
      dtype='object')

In [7]:
time_series = ds.groupby('Year')['Cited by'].mean()

In [8]:
time_series=time_series.to_frame()
time_series.to_csv('bda_citation_final',sep=',')

In [9]:
data = ds[['Authors', 'Title', 'Correspondence Address',
        'Source title']]

In [10]:
data['index'] = range(len(data))

In [11]:
data.isna().sum()

Authors                     0
Title                       0
Correspondence Address    197
Source title                0
index                       0
dtype: int64

In [12]:
features = [['Authors', 'Title', 'Correspondence Address',
        'Source title']]

In [13]:
for feature in features:
    data[feature]=data[feature].fillna('')

In [14]:
data.isna().sum()

Authors                   0
Title                     0
Correspondence Address    0
Source title              0
index                     0
dtype: int64

In [15]:
def combine_features(row):
    return row['Title']+" "+row['Correspondence Address']+" "+row['Source title']

In [16]:
data["Author_Details"]=data.apply(combine_features,axis=1)

In [17]:
data['Author_Details'][0]

'Polynomial-time algorithms for prime factorization and discrete logarithms on a quantum computer Shor, P.W.; AT and T Labs.-Research, 180 Park Avenue, Florham Park, NJ 07932, United States; email: shor@research.att.com SIAM Journal on Computing'

In [18]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to C:\Users\TEJA
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.


True

In [21]:
def cleaning(text):
    review = re.sub('[^a-zA-Z]',' ',text)
    return review
        
data['Author_Details'] = data['Author_Details'].apply(cleaning)

In [22]:
def lower(review):
    review=review.lower()
    #review=review.split()

    
    return review
data['Author_Details'] = data['Author_Details'].apply(lower)  

In [25]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\TEJA
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [26]:
stop = set(stopwords.words('english'))
stemmer = PorterStemmer()

In [28]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to C:\Users\TEJA
[nltk_data]     A\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.


True

In [29]:
def lemmatize(text):
    final_text=[]
    wordnet_lemmatizer = WordNetLemmatizer()
    token_words=word_tokenize(text)
    for word in token_words:
        
        if word not in stop:
            word = wordnet_lemmatizer.lemmatize(word)
            final_text.append(word)
    return " ".join(final_text) 
data['Author_Details'] = data['Author_Details'].apply(lemmatize)   
        

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(data['Author_Details'])

In [31]:
tfidf_matrix

<2000x8656 sparse matrix of type '<class 'numpy.float64'>'
	with 44952 stored elements in Compressed Sparse Row format>

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_scores = cosine_similarity(tfidf_matrix)
print(similarity_scores)

[[1.         0.00591724 0.07570961 ... 0.0358333  0.01363646 0.01434225]
 [0.00591724 1.         0.         ... 0.03964507 0.03141053 0.00250929]
 [0.07570961 0.         1.         ... 0.         0.00798629 0.00517964]
 ...
 [0.0358333  0.03964507 0.         ... 1.         0.04383187 0.0744262 ]
 [0.01363646 0.03141053 0.00798629 ... 0.04383187 1.         0.00715997]
 [0.01434225 0.00250929 0.00517964 ... 0.0744262  0.00715997 1.        ]]


In [33]:
def get_name_from_index(index):
    names=[]
    a=data[data.index == index]["Authors"]
    for key,value in enumerate(a):
        names.append(value)
    return names

def get_index_from_name(Author):
    indices=[]
    a=data[data.Authors == Author]["index"]
    for key,value in enumerate(a):
        indices.append(value)
    return indices


In [34]:
author_index = np.random.randint(0,len(data))
author = get_name_from_index(author_index)
author

['Degregorio N., Iyengar S.S.']

In [35]:
similar_Author_Scores=list(enumerate(similarity_scores[author_index]))

In [36]:
sorted_similar_Author_scores=sorted(similar_Author_Scores,key= lambda x:x[1],reverse=True)

In [37]:
sorted_similar_Author_scores

[(873, 1.0000000000000002),
 (1340, 0.6766437184031024),
 (326, 0.5649377502034966),
 (722, 0.533778740614187),
 (1186, 0.27656343033384034),
 (113, 0.1836907123871867),
 (828, 0.1804621484146482),
 (1749, 0.17729630278325254),
 (537, 0.15036158081767814),
 (717, 0.14466225725942908),
 (366, 0.14110870497296754),
 (63, 0.13889397604007903),
 (702, 0.1365808428736598),
 (1052, 0.13402826466612006),
 (1978, 0.13387235804593087),
 (670, 0.12534907791970734),
 (591, 0.12082845380936681),
 (1464, 0.11990079338673795),
 (682, 0.11914683175986242),
 (534, 0.1178987917421193),
 (773, 0.1137070028805601),
 (115, 0.11365087636158679),
 (168, 0.11342122699963808),
 (1238, 0.11254826280070002),
 (909, 0.11244908638969969),
 (871, 0.1123604689697127),
 (404, 0.10946553347824096),
 (1108, 0.10847703353558807),
 (334, 0.10676952607667502),
 (714, 0.1027517092970177),
 (26, 0.10186161487592815),
 (1952, 0.10165145402288098),
 (1030, 0.10044604675360992),
 (95, 0.09992568564425756),
 (1852, 0.099621041

In [38]:
co_authors = []
for key,value in enumerate(sorted_similar_Author_scores):
    if value[1]>=0.97:
        co = get_name_from_index(value[0])
        if co != author and co != '[]' :
            co_authors.append(co)
            print('Author {}-----already in Co_Author Relationship--------------> {}'.format(author,co))
    if value[1]>0.5 and value[1]<0.97:
        
        co = get_name_from_index(value[0])
        if co != author and co != '[]' :
            
            co_authors.append(co)
            print('Author {}----- Co_Author Relationship--------------> {}'.format(author,co))
        
    
    
   
    

Author ['Degregorio N., Iyengar S.S.']----- Co_Author Relationship--------------> ['Jakowski J., Sumner I., Iyengar S.S.']
Author ['Degregorio N., Iyengar S.S.']----- Co_Author Relationship--------------> ['Li J., Li X., Iyengar S.S.']
